// Shared constants for live captions / subtitles.

// Sentinel value for "no translation — show original language only".
export const CAPTIONS_OFF = "off";

// Target languages offered in the subtitle picker. OpenAI (gpt-4o-mini) handles
// the actual translation, so coverage is near-universal; this is just a curated,
// readable shortlist. Values are the human-readable labels passed straight to
// the translation prompt.
export const CAPTION_LANGUAGES: string[] = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Ukrainian",
  "Polish",
  "Turkish",
  "Arabic",
  "Hebrew",
  "Persian",
  "Urdu",
  "Hindi",
  "Bengali",
  "Punjabi",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Malay",
  "Filipino",
  "Swahili",
  "Greek",
  "Czech",
  "Slovak",
  "Hungarian",
  "Romanian",
  "Bulgarian",
  "Serbian",
  "Croatian",
  "Slovenian",
  "Finnish",
  "Swedish",
  "Norwegian",
  "Danish",
  "Icelandic",
  "Estonian",
  "Latvian",
  "Lithuanian",
  "Catalan",
  "Welsh",
  "Irish",
  "Afrikaans",
  "Amharic",
  "Zulu",
  "Hausa",
  "Yoruba",
  "Igbo",
  "Pashto",
  "Nepali",
  "Sinhala",
  "Khmer",
  "Lao",
  "Burmese",
  "Mongolian",
  "Kazakh",
  "Uzbek",
  "Azerbaijani",
  "Georgian",
  "Armenian",
];
